server:  
  port: ${PORT:9999}

spring:  
  application:
    name: auth-server
  datasource:
    url: jdbc:postgresql://localhost:5432/auth
    username: cacuware
    password: cacuware
    driver-class-name: org.postgresql.Driver

    
logging:
  level:
    org.springframework.security: DEBUG
